name: Build and Deploy Next.js Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18'

      - run: npm install
      - run: npm install sharp
      - run: npm run build

      - name: Ensure .next folder exists
        run: ls -la .next

      # Upload the .next folder as artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next
          if-no-files-found: warn
          overwrite: true
          include-hidden-files: true

    
    
