name: Build and Deploy Next.js Project

on:
  push:
    branches:
      - master  # Ganti dengan nama branch yang ingin kamu gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm install
    - run: npm install sharp
    - run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: .next # Ini adalah folder hasil build Next.js
